project_id = "beekrnfusoksullylvld"

[functions.get-google-maps-browser-key]
verify_jwt = false

[functions.get-google-maps-key]
verify_jwt = false

[functions.plaid-financial-connections]
verify_jwt = true