-- Add seed data
insert into public.resources
(title, description, category, state_code, county_name, tags, eligibility_summary, application_steps, documents_required, estimated_benefit_min, estimated_benefit_max, source_url, apply_url, contact_phone)
values
-- Federal
('IRS Publication 502 — Medical & Dental Expenses',
 'Official IRS guide to what medical and dental expenses are deductible, mileage rules, and documentation expectations.',
 'federal', null, null, '{tax,deductions,documentation}',
 'Taxpayers itemizing deductions may deduct qualified medical expenses above the IRS threshold; rules vary by expense type.',
 'Review eligible expenses; keep receipts/mileage logs; itemize on Schedule A; file with your federal return.',
 '{Receipts,Mileage log,Explanation of benefits}',
 null, null,
 'https://www.irs.gov/publications/p502',
 'https://www.irs.gov/filing',
 null),

('VITA & TCE — Free Tax Preparation',
 'Free tax prep by IRS-certified volunteers. TCE focuses on taxpayers 60+.',
 'federal', null, null, '{tax,free help,elderly}',
 'Generally for low-to-moderate income taxpayers; TCE prioritizes seniors.',
 'Find a nearby site; bring ID, SSNs/ITINs, W-2/1099s, medical expense records.',
 '{Photo ID,SSN/ITIN docs,Expense records}',
 null, null,
 'https://www.irs.gov/individuals/free-tax-return-preparation-by-volunteers',
 'https://www.irs.gov/individuals/free-tax-return-preparation-by-volunteers',
 null),

-- California
('In-Home Supportive Services (IHSS) — California',
 'Pays for services to help eligible aged, blind, or disabled persons remain safely at home.',
 'state', 'CA', null, '{home care,disability,caregiver support}',
 'California resident; meet Medi-Cal financial/functional criteria.',
 'Apply through county IHSS office; in-home assessment; get authorized hours.',
 '{ID,Medical verification,Medi-Cal info}',
 null, null,
 'https://www.cdss.ca.gov/in-home-supportive-services',
 'https://www.cdss.ca.gov/inforesources/ihss/apply',
 null),

('Paid Family Leave (PFL) — California',
 'Provides partial wage replacement when you take time off to care for a seriously ill family member.',
 'state', 'CA', null, '{leave,wage replacement,caregiver support}',
 'Covered by CA SDI; must have wage history and qualifying family member.',
 'File claim with EDD; verify medical certification; receive weekly benefits.',
 '{Medical certification,Wage history docs}',
 null, null,
 'https://edd.ca.gov/en/disability/paid-family-leave',
 'https://edd.ca.gov/en/disability/paid-family-leave/claim',
 null),

('Medi-Cal Home & Community-Based Services (HCBS) Waivers',
 'Waiver programs that cover long-term services/supports at home or in the community instead of institutions.',
 'state', 'CA', null, '{home care,waiver,disability}',
 'Financial and medical need; waiver-specific criteria apply.',
 'Identify relevant waiver; contact county; complete eligibility screening.',
 '{ID,Medical records,Financial records}',
 null, null,
 'https://www.dhcs.ca.gov/services/ltc/pages/hcbswaiver.aspx',
 'https://www.dhcs.ca.gov/services/ltc/pages/hcbswaiver.aspx',
 null),

-- Los Angeles County
('Los Angeles County Caregiver Resource Center',
 'Education, respite coordination, and counseling for unpaid family caregivers in LA County.',
 'county', 'CA', 'Los Angeles', '{respite,education,counseling}',
 'Unpaid family caregivers in Los Angeles County.',
 'Contact CRC; complete intake; get matched to services/resources.',
 '{ID,Care recipient info}',
 null, null,
 'https://www.caregivercenter.org/',
 'https://www.caregivercenter.org/get-help',
 null),

('LA County Medical Transportation Assistance',
 'Transportation support options and discounts for medical appointments within Los Angeles County.',
 'county', 'CA', 'Los Angeles', '{transportation,appointments}',
 'Varies by program; typically medical need and proof of appointment.',
 'Find eligible program; schedule ride; retain trip confirmations for records.',
 '{Appointment confirmation,ID}',
 null, null,
 'https://transit.lacounty.gov/',
 'https://transit.lacounty.gov/',
 null),

-- Nonprofit
('Alzheimer''s Association — Caregiver Support',
 'Local support groups, education, and a 24/7 helpline for dementia caregiving.',
 'nonprofit', null, null, '{caregiver support,education,elderly}',
 'Caregivers and families impacted by dementia/Alzheimer''s.',
 'Find a local chapter; join a support group; access care consults.',
 '{None}',
 null, null,
 'https://www.alz.org/help-support',
 'https://www.alz.org/',
 '800-272-3900'),

('Family Caregiver Alliance (FCA)',
 'Evidence-based caregiver education, state-by-state resource navigator, and direct support services.',
 'nonprofit', null, null, '{caregiver support,education,planning}',
 'Unpaid family caregivers (some services CA-focused via CRC network).',
 'Explore caregiver navigator; register for trainings; request consults.',
 '{None}',
 null, null,
 'https://www.caregiver.org/',
 'https://www.caregiver.org/connecting-caregivers/services-by-state/',
 null),

('AARP California Caregiver Resources',
 'Guides, checklists, and local programs tailored to California caregivers.',
 'nonprofit', 'CA', null, '{education,planning,caregiver support}',
 'Open access; select California state resources.',
 'Browse guides; download checklists; sign up for webinars.',
 '{None}',
 null, null,
 'https://www.aarp.org/caregiving/local/california-caregiver-resources/',
 'https://www.aarp.org/caregiving/local/california-caregiver-resources/',
 null);