// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://beekrnfusoksullylvld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJlZWtybmZ1c29rc3VsbHlsdmxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNDU1MDEsImV4cCI6MjA2MzYyMTUwMX0.3f1BK6yZAQqGPiVfyGve4mcCsGWsLVdA0Kbw0pgHleU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);